### PR TITLE
Update announcement.Rmd

### PR DESCRIPTION
**Pull request by MounaBelaid**

### CODE REVIEW

**Review by mcanouil — APPROVED** [review]
I updated the youtube URL with a shorter/prettier alias.

**Comment by MounaBelaid** [comment]
> I updated the R Lille Youtube URL with a shorter/prettier alias.

Yes that looks better. I will do the same for Tunis R User Group.

**Review by mcanouil — APPROVED** [review]

**Comment by mcanouil** [comment]
Ok, so let's keep this open a little bit.

PS: I updated the Meetup description with our Youtube channels.

**Comment by mcanouil** [comment]
I'll merge this.
Once you'll have the aliases for URLs, just open a new PR.

**Pull request merged**
